
version: '3.8'

services:
  # PostgreSQL database service
  postgres:
    container_name: Student-MIS_DB
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: jon
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Student-MIS_DB
    volumes:
      - postgres-data:/var/lib/postgresql/data

# Persistent volume for PostgreSQL data
volumes:
  postgres-data: